name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: rpkeys-mod-project
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'
      - run: chmod +x ./gradlew
      - run: ./gradlew build
      - name: Merge into one jar
        run: |
          mkdir -p build/combined
          python3 merge_jar.py base/svm-powers-rp.jar build/libs/rpkeys-1.0.0.jar build/combined/svm-powers-combined.jar
      - uses: actions/upload-artifact@v4
        with:
          name: svm-powers-combined
          path: rpkeys-mod-project/build/combined/*.jar
